<?php

namespace Adipsys\testBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	public function findAllContactsWithZipAndCountry()
	{
		/* return $this->getEntityManager()
		->createQuery(
				'SELECT c.id,c.firstName,c.lastName,a.zipCode,a.country FROM AdipsystestBundle:Contact c 
													INNER JOIN AdipsystestBundle:Address a'
		)
		->getResult(); */
		
		$queryBuilder = $this->createQueryBuilder('c')
							 ->select('c','a.zipCode','a.country')
							 ->from('Contact', 'c')
							 ->innerJoin('Address','a','c.id = a.contact_id');
		return $queryBuilder->getQuery()->getResult();
	}
}
